-- schema.sql

-- 表1: CATEGORY
CREATE TABLE IF NOT EXISTS CATEGORY (
    c_id SERIAL PRIMARY KEY,
    c_name VARCHAR(15) NOT NULL
);

-- 表2: ORGANIZER
CREATE TABLE IF NOT EXISTS ORGANIZER (
    o_id SERIAL PRIMARY KEY,
    o_name VARCHAR(15) NOT NULL,
    contact_info VARCHAR(15)
);

-- 表3: EVENT
CREATE TABLE IF NOT EXISTS EVENT (
    e_id SERIAL PRIMARY KEY,
    e_name VARCHAR(15) NOT NULL,
    c_id INT NOT NULL,
    o_id INT NOT NULL,
    e_datetime TIMESTAMP NOT NULL,
    e_location VARCHAR(15) NOT NULL,
    description TEXT,
    FOREIGN KEY (c_id) REFERENCES CATEGORY(c_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (o_id) REFERENCES ORGANIZER(o_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 表4: TICKET
CREATE TABLE IF NOT EXISTS TICKET (
    t_id SERIAL PRIMARY KEY,
    e_id INT NOT NULL,
    t_type VARCHAR(10) NOT NULL,
    price DECIMAL(10,2) NOT NULL CHECK (price > 0),
    total_quantity INT NOT NULL CHECK (total_quantity >= 0),
    remain_quantity INT NOT NULL CHECK (remain_quantity >= 0),
    FOREIGN KEY (e_id) REFERENCES EVENT(e_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 表5: CUSTOMER
CREATE TABLE IF NOT EXISTS CUSTOMER (
    cu_id SERIAL PRIMARY KEY,
    cu_name VARCHAR(15) NOT NULL,
    email VARCHAR(15) UNIQUE NOT NULL,
    phone_number VARCHAR(15),
    address TEXT,
    pwd VARCHAR(128) NOT NULL,
    role VARCHAR(10) NOT NULL DEFAULT 'User'
);

-- 表6: ORDER
CREATE TABLE IF NOT EXISTS "ORDER" (
    or_id SERIAL PRIMARY KEY,
    cu_id INT NOT NULL,
    or_date TIMESTAMP NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL CHECK (total_amount > 0),
    payment_status VARCHAR(10) NOT NULL DEFAULT 'Pending',
    is_canceled BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (cu_id) REFERENCES CUSTOMER(cu_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 表7: ORDER_DETAIL
CREATE TABLE IF NOT EXISTS ORDER_DETAIL (
    or_id INT NOT NULL,
    t_id INT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    subtotal DECIMAL(10,2) NOT NULL CHECK (subtotal > 0),
    PRIMARY KEY (or_id, t_id),
    FOREIGN KEY (or_id) REFERENCES "ORDER"(or_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (t_id) REFERENCES TICKET(t_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 表8: PAYMENT
CREATE TABLE IF NOT EXISTS PAYMENT (
    p_id SERIAL PRIMARY KEY,
    or_id INT NOT NULL,
    payment_method VARCHAR(10) NOT NULL,
    payment_datetime TIMESTAMP NOT NULL,
    amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
    FOREIGN KEY (or_id) REFERENCES "ORDER"(or_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 表9: VENUE
CREATE TABLE IF NOT EXISTS VENUE (
    v_id SERIAL PRIMARY KEY,
    v_name VARCHAR(15) NOT NULL,
    address TEXT,
    capacity INT NOT NULL CHECK (capacity > 0),
    contact_info VARCHAR(15)
);

-- 表10: EVENT_VENUE
CREATE TABLE IF NOT EXISTS EVENT_VENUE (
    e_id INT NOT NULL,
    v_id INT NOT NULL,
    arrangement TEXT,
    PRIMARY KEY (e_id, v_id),
    FOREIGN KEY (e_id) REFERENCES EVENT(e_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (v_id) REFERENCES VENUE(v_id) ON DELETE CASCADE ON UPDATE CASCADE
);
